title = "Speechly Docs"
theme = "speechly-docs"
publishDir = "docs"
baseUrl = "https://docs.speechly.com/"
copyright = "Speechly"
languageCode = "en"
enableGitInfo = true
disablePathToLower = true

[markup.goldmark.renderer]
unsafe= true

[markup.tableOfContents]
startLevel = 1
endLevel = 2
ordered = false

[markup.highlight]
style = "solarized-dark"

[taxonomies]
category = "categories"

[params]
description = "Developer tools for next-generation voice user interfaces"
icon_set = "ionicons"

[params.colors]
secondary = "#302666"
primary = "#53A3F9"

[outputs]
home = ["HTML", "JSON"]

[[params.fonts]]
name = "Avenir"
sizes = [400]
type = "sans_serif"

[[params.fonts]]
name = "Sansation"
sizes = [800]
type = "bold"

[[params.fonts]]
name = "Roboto Mono"
sizes = [600]
type = "monospace"

[[menu.main]]
name = "Docs"
identifier = "docs"
url = "/"
weight = 1

[[menu.main]]
name = "API References"
url = "/speechly-api/api-reference/"
weight = 2

[[menu.main]]
name = "GitHub" 
url = "https://github.com/speechly/"
weight = 3

[[menu.main]]
name = "Speechly website"
url = "https://www.speechly.com/"
weight = 4
