title = "Speechly Docs"
theme = "speechly-docs"
publishDir = "docs"
baseUrl = "https://docs.speechly.com/"
copyright = "Speechly"
languageCode = "en"
enableGitInfo = true
disablePathToLower = true

[markup.goldmark.renderer]
unsafe= true

[markup.tableOfContents]
startLevel = 1
endLevel = 2
ordered = false

[markup.highlight]
style = "solarized-dark"

[taxonomies]
category = "categories"

[params]
description = "Speechly is the Fast, Accurate, and Simple Voice Interface API for Web and Mobile Apps"
icon_set = "ionicons"

[params.colors]
secondary = "#0f1923"
primary = "#009FFA"

[outputs]
home = ["HTML", "JSON"]

[[params.fonts]]
name = "DM Sans"
sizes = [400, 500, 700]
type = "sans_serif"

[[params.fonts]]
name = "Roboto Mono"
sizes = [400, 600]
type = "monospace"

[[menu.main]]
name = "Menu"
weight = 1

[[menu.main]]
name = "Docs Home"
url = "/"
weight = 1
parent = "Menu"

[[menu.main]]
name = "Quick Start"
url = "/quick-start/"
weight = 2
parent = "Menu"

[[menu.main]]
name = "Client Libraries"
url = "/client-libraries/"
weight = 3
parent = "Menu"

[[menu.main]]
name = "UI Components"
url = "/ui-components/"
weight = 4
parent = "Menu"

[[menu.main]]
name = "Configuration"
url = "/slu-examples/"
weight = 5
parent = "Menu"

[[menu.main]]
name = "Development Tools"
url = "/dev-tools/"
weight = 6
parent = "Menu"

[[menu.main]]
name = "Examples"
url = "/examples/"
weight = 7
parent = "Menu"

[[menu.main]]
name = "Design Philosophy"
url = "/design-philosophy/"
weight = 8
parent = "Menu"

[[menu.main]]
name = "Speechly gRPC API"
url = "/speechly-api/"
weight = 9
parent = "Menu"

[[menu.main]]
name = "FAQ"
url = "/faq/"
weight = 10
parent = "Menu"

[[menu.main]]
name = "Product Updates"
url = "/release-notes/"
weight = 11
parent = "Menu"

[[menu.main]]
name = "Website"
weight = 2
url = "https://www.speechly.com"

[[menu.main]]
name = "GitHub"
url = "https://github.com/speechly/"
weight = 3

[[menu.main]]
name = "npm"
url = "https://www.npmjs.com/org/speechly"
weight = 4
