[build]
  publish = "docs"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.78.2"

[[redirects]]
  from = "/client-libraries/react-client/"
  to = "/client-libraries/react/"
  status = 301

[[redirects]]
  from = "/client-libraries/ui-libraries/"
  to = "/ui-libraries/"
  status = 301

[[redirects]]
  from = "/client-libraries/ui-libraries/*"
  to = "/ui-libraries/:splat"
  status = 301

[[redirects]]
  from = "/client-libraries/voice-forms/"
  to = "/ui-libraries/voice-forms/"
  status = 301

[[redirects]]
  from = "/client-libraries/voice-forms/*"
  to = "/ui-libraries/voice-forms/:splat"
  status = 301

[[redirects]]
  from = "/dev-tools/command-line-client/"
  to = "/dev-tools/command-line-tool/"
  status = 301

[[redirects]]
  from = "/slu-examples/example-configuration/"
  to = "/examples/"
  status = 301

[[redirects]]
  from = "/slu-examples/example-configuration/*"
  to = "/examples/:splat"
  status = 301

[[headers]]
  for = "/release-notes/index.json"
    [headers.values]
    Access-Control-Allow-Origin = "*"
