asr_biasing: moderate
entities:
  - name: device
    type: string
  - name: location
    type: string
    output_field: 1
templates: |
  rooms = [kitchen|bedroom|living room|closet|pantry|hallway|everywhere|all rooms|every room](location)
  room = [{in} {the} $rooms]
  list_of_rooms = [$room { {and} $room { {and} $room} }]
  devices = [lights|television|radio|everything|all devices|every device](device)
  device = [{the} {$rooms} $devices]
  list_of_devices = [$device { {and} $device { {and} $device} }]
  command = [turn|set|switch|put]
  intent = [
      *turn_on {$command} $list_of_devices on {$list_of_rooms}
      *turn_on $command on $list_of_devices {$list_of_rooms}
      *turn_off {$command} $list_of_devices off {$list_of_rooms}
      *turn_off $command off $list_of_devices {$list_of_rooms}
  ]
  $intent {and $intent}